import requests
import time
import random
from fake_useragent import UserAgent

views = input("\nIncrease Views and Votes")
delay_list = [5, 6, 7, 8, 9, 10]
ua = UserAgent()
views_headers = {'User-Agent': ua.random}
votes_headers = {'User-Agent': ua.random, 'Referer': 'http://sennheiser-top50.com/bandprofile.aspx?bandsno=1088&view=visitors', 'X-Requested-With': 'XMLHttpRequest', 'X-MicrosoftAjax': 'Delta=true', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'Content-Length': '2241'}

payload = "ctl00%24ContentPlaceHolder1%24ScriptManager1=ctl00%24ContentPlaceHolder1%24upvote%7Cctl00%24ContentPlaceHolder1%24lbvotenow&__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwUKLTMwMTIyMDk4Mw9kFgJmD2QWAgIDD2QWAgIGD2QWIgICDw8WAh4EVGV4dAUKQWF2aXNoa2FhcmRkAgMPDxYCHghJbWFnZVVybAUmYmFuZHByb2ZpbGVwaWNzX2N1cnJlbnRzZWFzb24vMTA4OC5qcGdkZAIEDw8WAh8ABckERm9ybWVkIGJ5IG11c2ljaWFucyBjb21pbmcgZnJvbSB2YXJpZWQgYmFja2dyb3VuZHMsIEFhdmlzaGthYXIgaGFzIGNyZWF0ZWQgaXQmIzM5O3MgdW5pcXVlIHBsYWNlIGluIHRoZSBtdXNpY2FsIGNpcmN1aXQgb2YgUHVuZSBpbiB2ZXJ5IGxpdHRsZSB0aW1lLg0KIFdpdGggYWdncmVzc2l2ZSwgY2xhc3NpY2FsIHZvY2FscyBibGVuZGVkIHdpdGggaGVhdnksIHBvd2VyLXBhY2tlZCByaWZmczsgd2UgZGVmaW5lICYjMzk7RnVzaW9uJiMzOTsgaW4gb3VyIG93biwgc3BlY2lhbCB3YXkuIFdlIGxpa2UgdG8gcHJlc2VudCBJbmRpYW4gbXVzaWMgaW4gYSB3YXkgdGhhdCB3YXMgbmV2ZXIgcHJlc2VudGVkIGJlZm9yZS4NCiAgICAgICAgICAgICBBYXZpc2hrYWFyIGhhcyBiZWVuIGluIHRoZSBuZXdzLCByYWRpbyBhbmQgc29jaWFsIG1lZGlhIGluIHRoZSByZWNlbnQgcGFzdCBiZWNhdXNlIG9mIHRoZSB2YXJpb3VzIG11c2ljYWwgcmlwcGxlcyBpdCBpcyBjcmVhdGluZyB0aHJvdWdoIHRoZWlyIGxpdmUgcGVyZm9ybWFuY2VzIGFuZCB0aGVpciBvcmlnaW5hbCBjb21wb3NpdGlvbnMgZm9yIHZhcmlvdXMgb3RoZXIgcHJvamVjdHMuZGQCBQ8WAh4LXyFJdGVtQ291bnQCBBYIZg9kFgJmDxUCDFByaXlhbCBQYXdhcgVEcnVtc2QCAQ9kFgJmDxUCDFRhbm1heSBQYXdhcg9FbGVjdHJpYyBHdWl0YXJkAgIPZBYCZg8VAgxSdWNoYSBCb25kcmUGVm9jYWxzZAIDD2QWAmYPFQITQWR2YWl0IFZhaXNoYW1wYXlhbgtCYXNzIEd1aXRhcmQCBg8WAh4Dc3JjBXhodHRwczovL3cuc291bmRjbG91ZC5jb20vcGxheWVyLz91cmw9SFRUUFM6Ly9zb3VuZGNsb3VkLmNvbS91c2VyLTk2MjMzMjc3MS9zaGFua2FyYSZhbXA7YXV0b19wbGF5PXRydWUmc2hvd19hcnR3b3JrPXRydWVkAgcPDxYCHgdWaXNpYmxlaGRkAggPDxYCHwEFJWJhbmRsb2dvc19jdXJyZW50c2Vhc29uLzEwODgtbG9nby5qcGdkZAIJDw8WAh8ABQxJbmRpZSBGdXNpb25kZAIKDw8WAh8AZWRkAgsPDxYCHwAFA05pbGRkAgwPDxYCHwAFC01haGFyYXNodHJhZGQCDQ8PFgIfAAUKV2VzdCBJbmRpYWRkAg4PDxYCHwAFCTEtNSB5ZWFyc2RkAg8PDxYCHwRoZBYCAgEPDxYCHwRoZGQCEA8PFgIfAAUCLS1kZAIRD2QWAmYPZBYCAgEPDxYCHwAFBDExNDdkZAISDw8WAh8ABQQyMjM5ZGRkTGjnS3FvafM5FYieZlU40Qsp59M%3D&__VIEWSTATEGENERATOR=171A0125&__EVENTVALIDATION=%2FwEdAARYBASzcCizvHHiVSKHs22OfKHG3HViTUSgqB3u23YHFjiXmVBxGSXrUvLZiZg5vPH5QKTK0WUuXCBZD32x8ugaGZ8ZDp9zhKPV5g0j9I9YmWi8pns%3D&ctl00%24ContentPlaceHolder1%24hfbandsno=1088&ctl00%24ContentPlaceHolder1%24hfcookiesupport=&__ASYNCPOST=true&ctl00%24ContentPlaceHolder1%24lbvotenow=VOTE%20NOW"

for i in range(0,views):
	views_req = requests.get('http://sennheiser-top50.com/bandprofile.aspx?bandsno=1088&view=visitors', headers=views_headers)
	time.sleep(2)
	votes_req = requests.post('http://sennheiser-top50.com/bandprofile.aspx?bandsno=1088&view=visitors', headers=votes_headers, data=payload)
	print votes_req.reason
	i=i+1
	time.sleep(random.choice(delay_list))